name: Run SQL Migrations (basic)

on:
  workflow_dispatch: {}
  push:
    paths: ['supabase/migrations/*.sql']

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Apply all .sql (alphabetical)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # use 5432 host do banco com ?sslmode=require
        run: |
          set -e
          for f in $(ls -1 supabase/migrations/*.sql | sort); do
            echo "Applying $f"
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
