name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lockfile-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install (allow lockfile update)
        run: pnpm -r install --no-frozen-lockfile

      - name: Detect lockfile changes
        id: lockdiff
        run: |
          if git diff --quiet -- pnpm-lock.yaml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Auto-commit updated lockfile (same-repo PRs)
        if: >
          steps.lockdiff.outputs.changed == 'true' &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): update pnpm-lock.yaml"
          file_pattern: pnpm-lock.yaml

      - name: Fail run if lockfile changed (forces re-run on new commit)
        if: steps.lockdiff.outputs.changed == 'true'
        run: |
          echo "::error ::pnpm-lock.yaml was updated. CI will fail this run so the new commit re-triggers CI. Merge only after the next run is green."
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: lockfile-guard
    if: ${{ always() && needs.lockfile-guard.result == 'success' }}  # only build when lockfile is stable
    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm -r install --frozen-lockfile

      - name: Build all workspaces
        run: pnpm -r build
