name: Apply One SQL (URL + track)
on:
  workflow_dispatch:
    inputs:
      sql_url:
        description: 'raw URL do .sql'
        required: true
        type: string

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Ensure tracking table
        env: { DATABASE_URL: ${{ secrets.DATABASE_URL }} }
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
          create table if not exists public.schema_migrations(
            id bigserial primary key,
            file_url text not null,
            checksum text not null unique,
            applied_at timestamptz not null default now()
          );
          SQL
      - name: Apply if not applied
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SQL_URL: ${{ inputs.sql_url }}
        run: |
          set -e
          curl -fsSL "$SQL_URL" -o /tmp/migration.sql
          sum="$(sha256sum /tmp/migration.sql | awk '{print $1}')"
          exists=$(psql "$DATABASE_URL" -Atqc "select 1 from public.schema_migrations where checksum='${sum}'")
          if [ "$exists" = "1" ]; then
            echo "Já aplicada (checksum)."; exit 0;
          fi
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /tmp/migration.sql
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c \
            "insert into public.schema_migrations(file_url, checksum) values ('${SQL_URL}','${sum}')"
